// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.Samples.CodeLens
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodingWithCalvin.Samples.CodeLens";
        public const string Name = "CodingWithCalvin.Samples.CodeLens";
        public const string Description = @"Sample VSIX to demonstrate CodeLens extensbility point.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Coding With Calvin";
        public const string Tags = "";
    }
}
